#!/usr/bin/env python

from subprocess import CalledProcessError
from bitwarden_pyro.util.logger import BwLogger
import subprocess as sp
import json


class Vault:
    def __init__(self):
        self._items = None
        self._key = None

        self._logger = BwLogger().get_logger()

    def set_key(self, key):
        self._key = key

    def sync(self):
        try:
            self._logger.info("Syncing items with bitwarden")

            sync_cmd = f"bw sync --session {self._key}"
            sp.run(sync_cmd.split(), capture_output=True, check=True)
        except CalledProcessError:
            self._logger.error("Failed to force a bitwarden sync")
            raise SyncException

    def get_topt(self, guid):
        try:
            self._logger.info("Requesting TOPT from bitwarden")

            cmd = ['bw', '--session', self._key, 'get', 'totp', guid]
            proc = sp.run(cmd, capture_output=True)

            output = proc.stdout.decode("utf-8")
            if proc.returncode == 0:
                return output
            elif "No TOTP available for this login" in output:
                return None
            else:
                raise TotpException
        except CalledProcessError:
            self._logger.error("Failed to retrieve TOTP")
            raise TotpException

    def load_items(self):
        try:
            self._logger.info("Loading items from bw")
            load_cmd = f"bw list items --session {self._key}"

            proc = sp.run(load_cmd.split(), capture_output=True, check=True)
            items_json = proc.stdout.decode("utf-8")
            self._items = json.loads(items_json)

            return len(self._items)
        except CalledProcessError:
            self._logger.error("Failed to load vault items from bitwarden")
            return 0

    def get_items(self):
        return self._items

    def get_by_name(self, name):
        items = [i for i in self._items if i['name'] == name]
        if len(items) == 1:
            return items[0]
        else:
            return items


class VaultFormatter:
    DEDUP_MARKER = '+ '

    @staticmethod
    def unique_format(items):
        unique = {}
        for item in items:
            arr = unique.get(item['name'], [])
            arr.append(item)
            unique[item['name']] = arr

        strings = []
        for name, arr in unique.items():
            if len(arr) == 1:
                strings.append(name)
            else:
                strings.append(
                    f"{VaultFormatter.DEDUP_MARKER}{name}")

        return "\n".join(strings)

    @staticmethod
    def group_format(items):
        strings = []
        index = 1
        for item in items:
            strings.append(f"#{index}: {item['login']['username']}")
            index += 1

        return '\n'.join(strings)


class VaultException(Exception):
    """Base class for items generated by Vault"""
    pass


class LoadException(VaultException):
    """Raised when vault fails to load items"""
    pass


class SyncException(VaultException):
    """Raised when bitwarden fails to sync"""
    pass


class TotpException(VaultException):
    """Raised when retrieving a TOTOP fails"""
    pass
